### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [Zavizhenetc/Project__10_validation#2]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Нужно исправить** заголовок должен кратко отражать назначение проекта.

## Регулярные выражения
**Можно лучше** Квантификатор `{1}` можно не использовать. Он не играет никакой роли.

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
help@2domains.ru - доменное имя может включать в себя цифры (также как и часть до @ - имя пользователя)

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
`@gmail.com` - адрес электронной почты должен содержать имя пользователя (название)

**Можно лучше** следующие некорректные кейсы проходят валидацию
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол

### Номер телефона
**Нужно исправить** следующие корректные кейсы не проходят валидацию
+7 925-900-90-90
89259009090

**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
```
+7(925 900-90-90
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90
```

Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`http://google.ru/path/to/deep/` - корректное доменное имя + путь
`http://8.8.8.8:8080/page/to/deep#` + корректный IP+путь
`http://www.ya.ru:9000/` - корректное доменное имя + порт + слеш

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`http://www.ya.ю` - некорректная доменная зона, кириллица
`http://.ru` - отсутствует доменное имя
`zz` - отсутстсвуют протокол, доменное имя и доменная зона
` ` (пробел) - отсутствует адрес
`http://127.0..`  - некорректный IP, точка на конце
`http://127.0.0..` - некорректный IP, точка на конце)

**Comment by Zavizhenetc** [comment]
Правки внесены

**Comment by zlocate** [comment]
Добрый день. Остается еще несколько кейсов, требующих исправления
### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`x@gmail.com` - имя ящика может состоять из одного символа
`t2e-s_t@g-m2ail.academy` - имя пользователя может включать в себя несколько спецсимволов (не подряд)

### Адрес сайта 
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`https://mysite.23` - tld не может состоять только из цифр)

**Comment by Zavizhenetc** [comment]
поправил

**Comment by zlocate** [comment]
К сожалению в процессе починки этого кейса сломались другие :(
### Email:
Для email необходимо чтобы валидацию **одновременно** проходили следующие кейсы

**Нужно исправить** следующие корректные кейсы не проходят валидацию:
`x@gmail.com` - имя ящика может состоять из одного символа

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`@gmail.com`` - адрес электронной почты должен содержать имя пользователя (название)

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`http://x.com:30` - корректное доменное имя + номер порта.

Если необходимо приложу вам полный список кейсов для самопроверки.

**Comment by Zavizhenetc** [comment]
> 
 Если необходимо приложу вам полный список кейсов для самопроверки.
>
было бы отлично  
Жду список

**Comment by zlocate** [comment]
Email
```
Позитивные:
some2@2domains.ru - имя и домен могут содержать цифры
som-e@d-omains.ru - имя и домен могут содержать тире
some@x.com - доменное имя может состоять из одного символа
x@gmail.com - имя ящика может состоять из одного символа
t2e-s_t@g-m2ail.academy
some@mail.yandex.ru
some-extra-long-name@some.extra.long.domain.name

Негативные:
_@site.ru - имя ящика не может состоять только из спецсимволов
_some_@ya.ru - имя ящика не может начинаться и заканчиваться на спецсимвол
my---mail@site.ru - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным
@gmail.com - адрес электронной почты должен содержать имя пользователя (название)
test@.
test@.com
m#i#e@gmail.com
```

Адрес сайта
```
Адрес сайта:
Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
http://ya.ru
https://www.ya.ru
http://google.ru:98/
http://x.com:30
http://google.ru/path/to/deep/
http://my-next-site.ru
http://8.8.8.8:8080
http://8.8.8.8:8080/page/to/deep#
http://some.test.yandex.ru

Негативные кейсы:
Проверку проходит следующий некорректный адреc сайта:
http://www.ya.
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http:something.ru (отсутствуют `//` после протокола) 
zzz://ya.ru (некорректный протокол. Допустимы только http\https)
http:\\google.ru
 httP://google.ru 
http://google.ru:/path/to/deep
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://something (отсутствует доменная зона)
http://1. (некорректный IP, точка на конце)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
http://127. (некорректный IP, точка на конце)
http://127.0..  (некорректный IP, точка на конце)
http://127.0.0.. (некорректный IP, точка на конце) 
http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр) 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
```

**Comment by Zavizhenetc** [comment]
- [x] поправил

**Comment by Zavizhenetc** [comment]
> К сожалению в процессе починки этого кейса сломались другие :(
> 
> ### Email:
> Для email необходимо чтобы валидацию **одновременно** проходили следующие кейсы
> 
> **Нужно исправить** следующие корректные кейсы не проходят валидацию:
> `x@gmail.com` - имя ящика может состоять из одного символа
> 
> **Нужно исправить** следующие некорректные кейсы проходят валидацию
> `_@site.ru` - имя ящика не может состоять только из спецсимволов
> `_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
> `@gmail.com`` - адрес электронной почты должен содержать имя пользователя (название)
> 
> ### Адрес сайта
> **Нужно исправить** следующие корректные кейсы не проходят валидацию
> `http://x.com:30` - корректное доменное имя + номер порта.
> 
> Если необходимо приложу вам полный список кейсов для самопроверки.

все поправил.

**Comment by zlocate** [comment]
**Можно лучше** следующие некорректные адреса почты проходят валидацию
`-mail@ru.com` - адрес начинающийся с символа тире (как и любого другого спецсимвола) считается некорректным

**Comment by zlocate** [comment]
**Можно лучше** запись `(http|https)` эквивалентна `https?`
**Можно лучше** удалить неиспользуемый файл .nojekyll из репозитория.

**Comment by zlocate** [comment]
Добрый день. Работа принята. Буду рад если вы проработаете комментарии "можно лучше".

**Comment by Zavizhenetc** [comment]
> **Можно лучше** запись `(http|https)` эквивалентна `https?`
> **Можно лучше** удалить неиспользуемый файл .nojekyll из репозитория.

поправил 
 .nojekyll  необходим для БЭМ структуры на гитхабе , для "_" и "__" . или есть другие варианты ?

**Comment by zlocate** [comment]
> > **Можно лучше** запись `(http|https)` эквивалентна `https?`
> > **Можно лучше** удалить неиспользуемый файл .nojekyll из репозитория.
> 
> поправил
> .nojekyll необходим для БЭМ структуры на гитхабе , для "_" и "__" . или есть другие варианты ?

В данном проекте отсутствует файловая структура БЭМ (стили лежат в корневом `style.css`) поэтому его наличие не играет роли. В проекте с файловой системой БЭМ он действительно нужен :)
